# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(922, 581)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.openpose = QWidget()
        self.openpose.setObjectName(u"openpose")
        self.import_button = QPushButton(self.openpose)
        self.import_button.setObjectName(u"import_button")
        self.import_button.setGeometry(QRect(381, 110, 120, 41))
        font = QFont()
        font.setPointSize(10)
        self.import_button.setFont(font)
        self.process_button = QPushButton(self.openpose)
        self.process_button.setObjectName(u"process_button")
        self.process_button.setGeometry(QRect(390, 260, 101, 40))
        self.process_button.setFont(font)
        self.openpose_progress = QProgressBar(self.openpose)
        self.openpose_progress.setObjectName(u"openpose_progress")
        self.openpose_progress.setGeometry(QRect(280, 310, 331, 23))
        self.openpose_progress.setValue(24)
        self.status_label = QLabel(self.openpose)
        self.status_label.setObjectName(u"status_label")
        self.status_label.setGeometry(QRect(206, 390, 471, 51))
        font1 = QFont()
        font1.setPointSize(13)
        self.status_label.setFont(font1)
        self.status_label.setAlignment(Qt.AlignCenter)
        self.filepaths_list = QListWidget(self.openpose)
        QListWidgetItem(self.filepaths_list)
        self.filepaths_list.setObjectName(u"filepaths_list")
        self.filepaths_list.setGeometry(QRect(60, 190, 151, 192))
        self.clear_button = QPushButton(self.openpose)
        self.clear_button.setObjectName(u"clear_button")
        self.clear_button.setGeometry(QRect(60, 150, 151, 31))
        self.clear_button.setFont(font)
        self.batch_name = QTextEdit(self.openpose)
        self.batch_name.setObjectName(u"batch_name")
        self.batch_name.setGeometry(QRect(370, 190, 141, 31))
        self.batch_name.setFont(font)
        self.batch_name_label = QLabel(self.openpose)
        self.batch_name_label.setObjectName(u"batch_name_label")
        self.batch_name_label.setGeometry(QRect(380, 168, 121, 20))
        self.batch_name_label.setFont(font)
        self.batch_name_label.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.openpose, "")
        self.labeler = QWidget()
        self.labeler.setObjectName(u"labeler")
        self.fileList = QListWidget(self.labeler)
        self.fileList.setObjectName(u"fileList")
        self.fileList.setGeometry(QRect(20, 120, 241, 351))
        self.fileList.setAlternatingRowColors(False)
        self.fileList.setSelectionMode(QAbstractItemView.MultiSelection)
        self.btnGuard = QPushButton(self.labeler)
        self.btnGuard.setObjectName(u"btnGuard")
        self.btnGuard.setGeometry(QRect(690, 70, 81, 31))
        self.btnGuard.setStyleSheet(u"background-color: rgba(105, 155, 103, 160); border: none;")
        self.btnSelectDirectory = QPushButton(self.labeler)
        self.btnSelectDirectory.setObjectName(u"btnSelectDirectory")
        self.btnSelectDirectory.setGeometry(QRect(20, 80, 91, 23))
        self.imagePreview = QLabel(self.labeler)
        self.imagePreview.setObjectName(u"imagePreview")
        self.imagePreview.setGeometry(QRect(380, 120, 501, 351))
        self.imagePreview.setScaledContents(True)
        self.label = QLabel(self.labeler)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 281, 31))
        font2 = QFont()
        font2.setPointSize(17)
        font2.setBold(True)
        font2.setWeight(75)
        self.label.setFont(font2)
        self.lblSelectedDirectory = QLabel(self.labeler)
        self.lblSelectedDirectory.setObjectName(u"lblSelectedDirectory")
        self.lblSelectedDirectory.setGeometry(QRect(120, 80, 141, 21))
        self.btnJab = QPushButton(self.labeler)
        self.btnJab.setObjectName(u"btnJab")
        self.btnJab.setGeometry(QRect(800, 70, 81, 31))
        self.btnJab.setStyleSheet(u"background-color: rgba(255, 0, 0, 160); border: none;")
        self.lblSelectedFile = QLabel(self.labeler)
        self.lblSelectedFile.setObjectName(u"lblSelectedFile")
        self.lblSelectedFile.setGeometry(QRect(380, 70, 291, 31))
        font3 = QFont()
        font3.setPointSize(14)
        font3.setBold(False)
        font3.setWeight(50)
        self.lblSelectedFile.setFont(font3)
        self.generateDatasetButton = QPushButton(self.labeler)
        self.generateDatasetButton.setObjectName(u"generateDatasetButton")
        self.generateDatasetButton.setGeometry(QRect(640, 470, 241, 21))
        self.btnDeselect = QPushButton(self.labeler)
        self.btnDeselect.setObjectName(u"btnDeselect")
        self.btnDeselect.setGeometry(QRect(590, 70, 81, 31))
        self.btnDeselect.setStyleSheet(u"background-color: rgba(0, 0, 0, 60); border: none;")
        self.btnUppercut = QPushButton(self.labeler)
        self.btnUppercut.setObjectName(u"btnUppercut")
        self.btnUppercut.setGeometry(QRect(800, 20, 81, 31))
        self.btnUppercut.setStyleSheet(u"background-color: rgba(255, 150, 0, 160); border: none;")
        self.tabWidget.addTab(self.labeler, "")
        self.teach = QWidget()
        self.teach.setObjectName(u"teach")
        self.datasetSelectBtn = QPushButton(self.teach)
        self.datasetSelectBtn.setObjectName(u"datasetSelectBtn")
        self.datasetSelectBtn.setGeometry(QRect(380, 80, 111, 24))
        self.datasetLabel = QLabel(self.teach)
        self.datasetLabel.setObjectName(u"datasetLabel")
        self.datasetLabel.setGeometry(QRect(330, 50, 211, 16))
        self.datasetLabel.setAlignment(Qt.AlignCenter)
        self.modelLabel = QLabel(self.teach)
        self.modelLabel.setObjectName(u"modelLabel")
        self.modelLabel.setGeometry(QRect(330, 130, 211, 16))
        self.modelLabel.setAlignment(Qt.AlignCenter)
        self.modelName = QTextEdit(self.teach)
        self.modelName.setObjectName(u"modelName")
        self.modelName.setGeometry(QRect(360, 150, 141, 31))
        self.modelName.setFont(font)
        self.teachBtn = QPushButton(self.teach)
        self.teachBtn.setObjectName(u"teachBtn")
        self.teachBtn.setGeometry(QRect(380, 210, 111, 24))
        self.outputLabel = QLabel(self.teach)
        self.outputLabel.setObjectName(u"outputLabel")
        self.outputLabel.setGeometry(QRect(250, 270, 371, 131))
        self.outputLabel.setAlignment(Qt.AlignCenter)
        self.batchNameLabel = QLabel(self.teach)
        self.batchNameLabel.setObjectName(u"batchNameLabel")
        self.batchNameLabel.setGeometry(QRect(500, 80, 201, 21))
        self.batchNameLabel.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.teach, "")
        self.predict = QWidget()
        self.predict.setObjectName(u"predict")
        self.predict_progressbar = QProgressBar(self.predict)
        self.predict_progressbar.setObjectName(u"predict_progressbar")
        self.predict_progressbar.setEnabled(False)
        self.predict_progressbar.setGeometry(QRect(660, 100, 211, 23))
        self.predict_progressbar.setValue(0)
        self.status_label_2 = QLabel(self.predict)
        self.status_label_2.setObjectName(u"status_label_2")
        self.status_label_2.setGeometry(QRect(20, 20, 311, 51))
        self.status_label_2.setFont(font1)
        self.status_label_2.setAlignment(Qt.AlignCenter)
        self.predict_process_button = QPushButton(self.predict)
        self.predict_process_button.setObjectName(u"predict_process_button")
        self.predict_process_button.setEnabled(False)
        self.predict_process_button.setGeometry(QRect(490, 80, 121, 51))
        self.predict_process_button.setFont(font)
        self.predict_select_button = QPushButton(self.predict)
        self.predict_select_button.setObjectName(u"predict_select_button")
        self.predict_select_button.setGeometry(QRect(330, 30, 120, 31))
        self.predict_select_button.setFont(font)
        self.predict_clear_list = QPushButton(self.predict)
        self.predict_clear_list.setObjectName(u"predict_clear_list")
        self.predict_clear_list.setGeometry(QRect(50, 440, 241, 21))
        self.predict_clear_list.setFont(font)
        self.predict_image_preview = QLabel(self.predict)
        self.predict_image_preview.setObjectName(u"predict_image_preview")
        self.predict_image_preview.setGeometry(QRect(390, 220, 411, 231))
        self.predict_image_preview.setScaledContents(True)
        self.predict_filelist = QListWidget(self.predict)
        self.predict_filelist.setObjectName(u"predict_filelist")
        self.predict_filelist.setGeometry(QRect(50, 90, 241, 321))
        self.predict_filelist.setAlternatingRowColors(False)
        self.predict_filelist.setSelectionMode(QAbstractItemView.MultiSelection)
        self.predict_filename_label = QLabel(self.predict)
        self.predict_filename_label.setObjectName(u"predict_filename_label")
        self.predict_filename_label.setGeometry(QRect(330, 160, 121, 31))
        self.predict_filename_label.setFont(font1)
        self.predict_filename_label.setAlignment(Qt.AlignCenter)
        self.predict_confidence_label = QLabel(self.predict)
        self.predict_confidence_label.setObjectName(u"predict_confidence_label")
        self.predict_confidence_label.setGeometry(QRect(510, 160, 361, 31))
        self.predict_confidence_label.setFont(font1)
        self.predict_confidence_label.setAlignment(Qt.AlignCenter)
        self.batch_name_label_2 = QLabel(self.predict)
        self.batch_name_label_2.setObjectName(u"batch_name_label_2")
        self.batch_name_label_2.setGeometry(QRect(330, 80, 121, 20))
        self.batch_name_label_2.setFont(font)
        self.batch_name_label_2.setAlignment(Qt.AlignCenter)
        self.predict_batch_name = QTextEdit(self.predict)
        self.predict_batch_name.setObjectName(u"predict_batch_name")
        self.predict_batch_name.setGeometry(QRect(320, 102, 141, 31))
        self.predict_batch_name.setFont(font)
        self.predict_select_model = QPushButton(self.predict)
        self.predict_select_model.setObjectName(u"predict_select_model")
        self.predict_select_model.setGeometry(QRect(490, 30, 120, 31))
        self.predict_select_model.setFont(font)
        self.tabWidget.addTab(self.predict, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 922, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MMA Posture Labeler", None))
        self.import_button.setText(QCoreApplication.translate("MainWindow", u"Import Files", None))
        self.process_button.setText(QCoreApplication.translate("MainWindow", u"Process Files", None))
        self.status_label.setText(QCoreApplication.translate("MainWindow", u"READY", None))

        __sortingEnabled = self.filepaths_list.isSortingEnabled()
        self.filepaths_list.setSortingEnabled(False)
        ___qlistwidgetitem = self.filepaths_list.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"path/fileName", None));
        self.filepaths_list.setSortingEnabled(__sortingEnabled)

        self.clear_button.setText(QCoreApplication.translate("MainWindow", u"Clear List", None))
        self.batch_name_label.setText(QCoreApplication.translate("MainWindow", u"Enter Batch Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.openpose), QCoreApplication.translate("MainWindow", u"Keypoint Generator", None))
        self.btnGuard.setText(QCoreApplication.translate("MainWindow", u"Guard", None))
        self.btnSelectDirectory.setText(QCoreApplication.translate("MainWindow", u"Select directory", None))
        self.imagePreview.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Pose labeling", None))
        self.lblSelectedDirectory.setText("")
        self.btnJab.setText(QCoreApplication.translate("MainWindow", u"Jab", None))
        self.lblSelectedFile.setText("")
        self.generateDatasetButton.setText(QCoreApplication.translate("MainWindow", u"Generate dataset from selected frames", None))
        self.btnDeselect.setText(QCoreApplication.translate("MainWindow", u"Deselect", None))
        self.btnUppercut.setText(QCoreApplication.translate("MainWindow", u"Uppercut", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.labeler), QCoreApplication.translate("MainWindow", u"Labeling", None))
        self.datasetSelectBtn.setText(QCoreApplication.translate("MainWindow", u"Select Directory", None))
        self.datasetLabel.setText(QCoreApplication.translate("MainWindow", u"Select a Dataset to teach the model", None))
        self.modelLabel.setText(QCoreApplication.translate("MainWindow", u"Name the model", None))
        self.teachBtn.setText(QCoreApplication.translate("MainWindow", u"TEACH", None))
        self.outputLabel.setText(QCoreApplication.translate("MainWindow", u"Waiting..", None))
        self.batchNameLabel.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teach), QCoreApplication.translate("MainWindow", u"Teach", None))
        self.status_label_2.setText(QCoreApplication.translate("MainWindow", u"Import the files you want to predict", None))
        self.predict_process_button.setText(QCoreApplication.translate("MainWindow", u"Process Files", None))
        self.predict_select_button.setText(QCoreApplication.translate("MainWindow", u"Select Video File", None))
        self.predict_clear_list.setText(QCoreApplication.translate("MainWindow", u"Clear List", None))
        self.predict_image_preview.setText("")
        self.predict_filename_label.setText(QCoreApplication.translate("MainWindow", u"filename.jpeg", None))
        self.predict_confidence_label.setText(QCoreApplication.translate("MainWindow", u"Frame matches a jab with a confidence of 87%", None))
        self.batch_name_label_2.setText(QCoreApplication.translate("MainWindow", u"Enter Batch Name", None))
        self.predict_select_model.setText(QCoreApplication.translate("MainWindow", u"Select a model", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.predict), QCoreApplication.translate("MainWindow", u"Predict", None))
    # retranslateUi

